# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: postgres:16-alpine
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
      - POSTGRES_PASSWORD=Themakers2023
      - PGDATA=/var/lib/postgresql/data/pgdata
  odoo:
    image: docker.io/bitnami/odoo:17
    restart: always
    ports:
      - '8080:8069'
    
    volumes:
      - 'odoo_data:/bitnami/odoo'
      - ./custom-addons:/bitnami/odoo/addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./conf:/bitnami/odoo/conf/
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ODOO_DATABASE_ADMIN_PASSWORD=bitnami
      - ODOO_DATABASE_PASSWORD=Themakers2023
      - DB_HOST=postgresql

   
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local